@procedures/stat/nb_commentaires_news
@procedures/stat/note_moyenne_evenement
@procedures/creation/creer_personne
@procedures/creation/creer_association
@procedures/creation/creer_objectif
@procedures/creation/creer_news
@procedures/creation/creer_evenement
@procedures/creation/faire_commenter
@procedures/maj/maj_association
@procedures/maj/maj_bureau
@procedures/maj/maj_adherent