prompt [Création vue CLASSEMENT_ADHERENTS];
create view CLASSEMENT_ADHERENTS AS
select ADHERENTS.*, P_NOM, P_PRENOM, NB_EVENEMENTS from
(select ID_ADHERENT, COUNT(ID_EVENEMENT_PARTICIPE) NB_EVENEMENTS
  from PARTICIPATIONS
  right join ADHERENTS on ID_ADHERENT=ID_PERSONNE_PARTICIPANT
  group by ID_ADHERENT) SR
inner join ADHERENTS on ADHERENTS.ID_ADHERENT = SR.ID_ADHERENT
inner join PERSONNES on PERSONNES.ID_PERSONNE = ADHERENTS.ID_ADHERENT
order by NB_EVENEMENTS desc;
--) SR
--right join EVENEMENTS on EVENEMENTS.ID_EVENEMENT = SR.ID_EVENEMENT
--inner join CONTENUS on CONTENUS.ID_CONTENU = EVENEMENTS.ID_EVENEMENT
--order by NOTE_MOYENNE desc nulls last;