prompt [Création vue NOTES_MOYENNES_EVENEMENT];
create view NOTES_MOYENNES_EVENEMENT AS
select ID_EVENEMENT_PARTICIPE ID_EVENEMENT, AVG(NOTE) NOTE_MOYENNE
from PARTICIPATIONS
where not(NOTE is null)
group by ID_EVENEMENT_PARTICIPE;