prompt [Création vue CLASSEMENT_EVENEMENTS];
create view CLASSEMENT_EVENEMENTS AS
select EVENEMENTS.*, CONTENUS.DATE_PUBLICATION_CONTENU, CONTENUS.TITRE_CONTENU, NOTE_MOYENNE from
(select ID_EVENEMENT_PARTICIPE ID_EVENEMENT, AVG(NOTE) NOTE_MOYENNE
from PARTICIPATIONS
where not(NOTE is null)
group by ID_EVENEMENT_PARTICIPE) SR
right join EVENEMENTS on EVENEMENTS.ID_EVENEMENT = SR.ID_EVENEMENT
inner join CONTENUS on CONTENUS.ID_CONTENU = EVENEMENTS.ID_EVENEMENT
order by NOTE_MOYENNE desc nulls last;
-- Déclaration des objets créés
begin
    register_object('view', 'CLASSEMENT_EVENEMENTS');
end;
/